// src/app/services/service-process-item.tsx
type Process = {
  title: string
  desc: string
}

type Props = {
  position: number
  process: Process
}

export function ServiceProcessItem({ position, process }: Props) {
  return (
    <div
      className="flex flex-col p-6 rounded-2xl border border-gray-100 dark:border-gray-800 gap-6"
      data-cursor-size="80"
      data-cursor-exclusion
      data-animation-target
    >
      <h3 className="text-2xl font-medium leading-tight">
        {position + 1}. {process.title}
      </h3>
      <p className="text-lg leading-relaxed">{process.desc}</p>
    </div>
  )
}

// apps/web/components/service/ServiceProcessItem.vue
<template>
  <div
    ref="itemRef"
    class="flex flex-col p-6 rounded-2xl border border-gray-100 dark:border-gray-800 gap-6"
    data-cursor-size="80"
    data-cursor-exclusion
  >
    <h3 class="text-2xl font-medium leading-tight">
      {{ position + 1 }}. {{ data.title }}
    </h3>
    <p class="text-lg leading-relaxed">
      {{ data.desc }}
    </p>
  </div>
</template>

<script setup lang="ts">
const itemRef = ref<HTMLDivElement>()

interface ServiceProcessItemProps {
  position: number
  data: {
    title: string
    desc: string
  }
}
defineProps<ServiceProcessItemProps>()
</script>
