// apps/frontend/pages/blog/[...slug].tsx
import ContentPortable from '@components/content/portable-content'
import { BlogDetailLayout } from '@components/layouts'
import contentService from '@lib/services/content-service'
import { QueryClient, dehydrate, useQuery } from '@tanstack/react-query'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { NextPageWithLayout } from '~/types/app'

interface BlogDetailPageProps {
  slug: string
}

/**
 * # BlogDetailPage
 *
 * Detail page to showing the blog pages
 * that's contain the header, footer, and sidebar
 *
 * @returns JSX.Element
 */
const BlogDetailPage: NextPageWithLayout<BlogDetailPageProps> = ({ slug }) => {
  const detailQuery = useQuery(['blog', slug], () =>
    contentService.getDetailBlog(slug)
  )

  return (
    <>
      <Head>
        <title>{detailQuery.data?.title} | Nyoman Sunima</title>
        <meta
          name="description"
          content={detailQuery.data?.desc.substring(0, 100)}
        />
      </Head>

      {/* showing actual content */}
      {detailQuery.data && (
        <article className="flex w-full flex-col p-5 border border-gray-100 rounded-3xl overflow-hidden">
          {/* thumbnail */}
          <picture className="flex w-full relative h-[500px] rounded-2xl overflow-hidden">
            <Image
              src={detailQuery.data.thumbnail}
              alt={detailQuery.data.title}
              fill
              sizes="auto"
              className="object-cover"
            />
          </picture>

          {/* tags */}
          <div className="flex flex-wrap items-center gap-x-5 mt-10">
            {detailQuery.data.tags.map((tag, index) => (
              <span
                className="flex items-center justify-center px-4 py-2 rounded-full text-indigo-600 bg-indigo-100 font-medium"
                key={index}
              >
                {tag.title}
              </span>
            ))}
          </div>

          {/* title */}
          <h1 className="flex text-5xl font-medium mt-10 border-b border-b-gray-100 pb-5">
            {detailQuery.data.title}
          </h1>

          {/* actual content */}
          <ContentPortable
            content={detailQuery.data.content}
            className="px-3"
          />
        </article>
      )}
    </>
  )
}

BlogDetailPage.layout = (page) => {
  return <BlogDetailLayout>{page}</BlogDetailLayout>
}

const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const slug = params!.slug![0] as string
  if (!slug) {
    return {
      redirect: {
        destination: '/blog',
        permanent: false,
      },
    }
  }

  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(['blog', slug], () =>
    contentService.getDetailBlog(slug)
  )

  return {
    props: {
      slug,
      dehydratedState: dehydrate(queryClient),
    },
  }
}

export { getServerSideProps }
export default BlogDetailPage

// apps/web/pages/blog/[slug].vue
<template>
  <main class="flex flex-col laptop:py-60 laptop:pb-80 py-28 pb-28">
    <!-- top action including back, share and other -->
    <div class="container mx-auto px-5">
      <div class="flex laptop:w-7/12 mx-auto">
        <TextButton @click="navigateTo('/blog')"
          ><i class="fi fi-rr-arrow-left text-2xl"></i> Back to
          overview</TextButton
        >
      </div>
    </div>

    <!-- content articles -->
    <div class="flex flex-col container mx-auto mt-20">
      <article
        class="flex flex-col w-11/12 laptop:w-7/12 mx-auto border-b border-gray-100 dark:border-b-gray-800 pb-10"
      >
        <!-- title -->
        <h1 class="text-5xl font-medium leading-tight">
          {{ post.title }}
        </h1>
        <!-- release date -->
        <span class="text-gray-500 text-lg mt-3">{{ parsedReleaseDate }}</span>
        <picture
          class="flex relative overflow-hidden w-full h-[400px] rounded-3xl mt-10"
        >
          <NuxtImg :src="post.thumbnail" class="flex w-full" />
        </picture>

        <!-- tags -->
        <div class="flex flex-wrap gap-x-3 gap-y-3 mt-10">
          <BlogTag v-for="tag in post.tags" :key="tag" :tag="tag" />
        </div>

        <!-- content -->
        <MarkdownContent :data="post.content" />
      </article>

      <!-- the article author -->
      <BlogPostAuthor />
    </div>

    <!-- Related posts -->
    <BlogRelatedPost :data="related" v-show="related.length > 0" />
  </main>
</template>

<script setup lang="ts">
import { BlogDetail } from '~/types/content'

definePageMeta({
  layout: 'blog'
})

const route = useRoute()

// fetching the post including with
// related posts
const query = `
  {
    "post": *[_type == "blog" && slug.current == $slug][0]{
      ...,
      "thumbnail": thumbnail.asset -> url,
    },
    "related": *[_type == "blog" && slug.current != $slug] | order(_createdAt desc) [0...3]{
      "slug": slug.current,
      title,
      "thumbnail": thumbnail.asset -> url,
      "tag": tags[0],
      _createdAt,
      featured,
    }
  }
`
const {
  data: {
    value: { post, related }
  }
} = await useSanityQuery<BlogDetail>(query, {
  slug: route.params.slug
})

// parse the date into readable string
const parsedReleaseDate = computed(() =>
  parseDateToRelative(new Date(post._createdAt))
)

useHead({
  title: post.title,
  meta: [
    {
      name: 'description',
      content: post.desc.substring(0, 100)
    }
  ]
})
</script>
