// src/app/blog/blog-post-item.tsx
import Image from 'next/image'
import Link from 'next/link'
import { Post } from '~/types'
import * as React from 'react'

type Props = {
  post: Post
}

type BlogTagProps = {
  tags: string[]
}

type BlogPillProps = {
  children: React.ReactNode
}

function BlogTag({ tags }: BlogTagProps) {
  return (
    <span className="absolute top-4 right-4 px-5 text-sm py-2 rounded-full bg-background border border-border">
      {tags[0]}
    </span>
  )
}

function BlogPill({ children }: BlogPillProps) {
  return (
    <span className="flex gap-2 px-4 text-sm py-2 rounded-full bg-background border border-border">
      {children}
    </span>
  )
}

export function BlogPostItemCard({ post }: Props) {
  const postURL = `/blog/${post.slug}`

  return (
    <Link href={postURL} className="flex flex-col w-full">
      <picture className="relative w-full h-[450px] overflow-hidden rounded-2xl">
        <Image
          src={post.image}
          alt={post.title}
          fill
          className="object-cover transition-all duration-1000 hover:scale-105"
        />

        <BlogTag tags={post.tags} />
        <div className="flex items-center gap-2 absolute bottom-4 left-4">
          <BlogPill>
            <i className="fi fi-rr-video-camera-alt" />
            {post.totalViews}
          </BlogPill>
          <BlogPill>
            <i className="fi fi-rr-face-awesome" />
            {post.reactionCount}
          </BlogPill>
        </div>
      </picture>

      <h3 className="mt-6 text-2xl !leading-tight line-clamp-2">
        {post.title}
      </h3>
    </Link>
  )
}

// apps/web/components/blog/BlogPostItem.vue
<template>
  <div
    class="flex flex-col col-span-2 row-span-6 transition-all duration-300 hover:-translate-y-2 cursor-pointer"
    :class="class"
    @click="openPost"
  >
    <div
      class="flex h-[320px] laptop:h-[480px] relative rounded-3xl overflow-hidden"
    >
      <!-- categories -->
      <div
        class="flex bg-white px-5 h-12 rounded-full gap-3 absolute right-5 top-5 justify-center items-center z-10"
      >
        <span class="h-2 w-2 rounded-full bg-black"></span>
        <span class="text-base font-medium">{{ data.tag }}</span>
      </div>

      <!-- release date -->
      <div
        class="flex justify-center items-center bg-white px-5 h-12 rounded-full gap-3 absolute text-gray-600 text-base left-5 bottom-5 z-10"
      >
        {{ parsedDate }}
      </div>

      <!-- thumbnail -->
      <NuxtImg
        :src="data.thumbnail"
        class="h-full w-full object-cover transition-all duration-1000 hover:scale-105"
      />
    </div>

    <h3
      class="text line-clamp-2 font-semibold mt-8 w-10/12 leading-snug"
      :class="size === 'large' ? 'text-3xl' : 'text-2xl'"
    >
      {{ data.title }}
    </h3>
  </div>
</template>

<script setup lang="ts">
import { BlogPost } from '~/types/content'

interface BlogPostItemProps {
  class?: string
  size?: 'medium' | 'large'
  data: BlogPost
}

const { size = 'medium', data } = defineProps<BlogPostItemProps>()
const parsedDate = computed(() => {
  return parseDateToRelative(new Date(data._createdAt))
})

const openPost = () => {
  navigateTo(`/blog/${data.slug}`)
}
</script>
