// apps/frontend/components/blog/blog-related-post.tsx
import { FunctionComponent } from 'react'
import BlogRelatedPostItem from './blog-related-post-item'

/**
 * # BlogRelatedPost
 *
 * section to show the related post after
 * the user reach the end of post
 *
 * @returns JSX.Element
 */
const BlogRelatedPost: FunctionComponent = (): JSX.Element => {
  return (
    <div className="flex flex-col gap-14 mt-24 container mx-auto px-10">
      <h4 className="flex w-full border-b border-b-gray-100 pb-3 text-4xl font-semibold">
        Related Post
      </h4>

      <div className="flex w-full gap-6">
        {[1, 2, 3].map((index) => (
          <BlogRelatedPostItem key={index} />
        ))}
      </div>
    </div>
  )
}

export default BlogRelatedPost

// apps/web/components/blog/BlogRelatedPost.vue
<template>
  <div class="flex flex-col container mx-auto px-10 mt-80">
    <h3 class="text-4xl font-semibold">Related posts</h3>
    <div class="grid grid-cols-6 mt-10 gap-6">
      <BlogPostItem :data="post" v-for="post in data" :key="post.slug" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { BlogPost } from '~/types/content'

interface BlogRelatedPostProps {
  data: BlogPost[]
}
defineProps<BlogRelatedPostProps>()
</script>
