// apps/frontend/components/headers/blog-header.tsx
import { IconButton } from '@components/buttons'
import Image from 'next/image'
import Link from 'next/link'
import { FunctionComponent } from 'react'

interface Menu {
  label: string
  path: string
}

const menuList: Menu[] = [
  {
    label: 'Tips',
    path: 'tips',
  },
  {
    label: 'Journey',
    path: 'journey',
  },
  {
    label: 'Process',
    path: 'process',
  },
  {
    label: 'Design',
    path: 'design',
  },
  {
    label: 'Development',
    path: 'development',
  },
]

/**
 * # BlogHeader
 *
 * Header for blog
 *
 * @returns JSX.Element
 */
const BlogHeader: FunctionComponent = (): JSX.Element => {
  const navigatePath = (path: string) => {}

  return (
    <header className="flex fixed z-10 top-0 inset-x-0 bg-white border-b border-b-gray-100 px-10 py-4 items-center">
      {/* brand */}
      <Link
        href={'/'}
        className="flex items-center text-xl font-medium gap-3 z-10"
      >
        <Image src={'/images/logo.png'} height={40} width={40} alt="Logo" />
        Blog
      </Link>

      {/* navigations */}
      <div className="flex flex-1"></div>
      <div className="flex flex-1 gap-5 items-center">
        {menuList.map((menu, index) => (
          <button
            className="flex items-center justify-center px-2 py-1 rounded-md font-semibold"
            key={index}
            onClick={() => navigatePath(menu.path)}
          >
            {menu.label}
          </button>
        ))}
      </div>

      {/* the full menu */}
      <IconButton>
        <i className="fi fi-rr-search"></i>
      </IconButton>
    </header>
  )
}

export default BlogHeader

// apps/web/components/blog/BlogHeader.vue
<template>
  <header
    class="flex fixed z-10 top-0 inset-x-0 bg-white bg-opacity-50 backdrop-blur-sm border-b border-b-gray-100 px-14 py-3"
    s
  >
    <!-- branding -->
    <div class="flex items-center gap-2">
      <NuxtLink to="/" class="h-10 w-10 relative">
        <NuxtImg src="/images/logo.png" />
      </NuxtLink>
      <NuxtLink to="/blog" class="text-xl font-semibold">Blog</NuxtLink>
    </div>

    <!-- menus -->
    <div class="flex flex-1"></div>
    <ul class="flex items-center gap-6 mr-16">
      <li
        class="flex items-center font-medium cursor-pointer transition-all duration-300 hover:-translate-y-1"
        v-for="menu in menus"
        :key="menu.path"
      >
        {{ menu.label }}
      </li>
    </ul>

    <!-- another buttons -->
    <IconButton
      @click="
        () => {
          console.log('Hello')
        }
      "
    >
      <i class="fi fi-rr-search"></i>
    </IconButton>
  </header>
</template>

<script setup lang="ts">
interface Menu {
  label: string
  path: string
}

const menus: Menu[] = [
  {
    label: 'Tips',
    path: 'tips'
  },
  {
    label: 'Development',
    path: 'development'
  },
  {
    label: 'Design',
    path: 'design'
  }
]
</script>
