// apps/web/components/ui/Button.vue
<script lang="ts" setup>
import { cva, VariantProps } from 'class-variance-authority'
import { ButtonHTMLAttributes } from 'nuxt/dist/app/compat/capi'

const buttonVariants = cva(
  'flex justify-center items-center text-base font-medium gap-3',
  {
    variants: {
      variant: {
        primary: 'bg-black text-neutral-100 dark:bg-white dark:text-black',
        outline: 'border border-neutral-100 dark:border-neutral-800',
        secondary: 'bg-neutral-100 dark:bg-neutral-900',
      },
      size: {
        base: 'px-7 h-12 rounded-full',
        sm: 'text',
        md: '',
        lg: 'px-8 h-16 text-lg rounded-full',
        xl: '',
        icon: 'h-12 w-12 rounded-full',
      },
    },
    defaultVariants: {
      variant: 'outline',
      size: 'base',
    },
  },
)

export interface ButtonProps extends /* @vue-ignore */ ButtonHTMLAttributes {
  size?: VariantProps<typeof buttonVariants>['size']
  variant?: VariantProps<typeof buttonVariants>['variant']
  asChild?: boolean
  as?: string
}
const { size, variant } = defineProps<ButtonProps>()

const buttonClass = computed(() =>
  mergeClass(buttonVariants({ size, variant })),
)
</script>

<template>
  <slot v-if="asChild" />
  <component :is="as ?? 'button'" v-else :class="buttonClass">
    <slot />
  </component>
</template>

// src/components/ui/button.tsx
import * as React from 'react'
import { Slot } from '@radix-ui/react-slot'
import { cva, type VariantProps } from 'class-variance-authority'
import { mergeClass } from '~/utils/helpers'

const buttonVariants = cva('flex justify-center items-center relative gap-3', {
  variants: {
    variant: {
      primary: 'bg-primary text-primary-foreground',
      outline: 'border border-border',
      secondary: 'bg-secondary text-secondary-foreground',
    },
    size: {
      base: 'h-12 px-6 py-2 rounded-xl text-base',
      sm: 'h-9 rounded-md px-3',
      lg: 'h-11 rounded-md px-8',
      md: 'h-16 px-10 rounded-full text-lg',
      icon: 'h-11 w-11 rounded-full',
    },
  },
  defaultVariants: {
    variant: 'primary',
    size: 'md',
  },
})

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button'
    return (
      <Comp
        className={mergeClass(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  },
)
Button.displayName = 'Button'

export { Button, buttonVariants }
